name:                CardJitsu-Haskell
version:             0.1.0.0
github:              "githubuser/CardJitsu-Haskell"
license:             BSD-3-Clause
author:              |
  David Joshua Galvíncio de Souza <david.joshua.galvincio.souza@ccc.ufcg.edu.br>,
  Gabriel Cavalcanti Araujo <gabriel.cavalcanti.araujo@ccc.ufcg.edu.br>
maintainer:          "example@example.com"
copyright:           "2024 David Gabriel"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/CardJitsu-Haskell#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- tasty
- tasty-hunit
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  CardJitsu-Haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CardJitsu-Haskell

tests:
  CardJitsu-Haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CardJitsu-Haskell
    - tasty
    - tasty-hunit
    - random
